module.exports = Object.freeze({
    EMPLOYEE_INVITATION_SMS: "Hello {{firstname}},%0D%0AWelcome to L-ROI. You can install the L-ROI application from play store and login with your mobile number.%0D%0AThank you,%0D%0AL-ROI Team.",
    FORGOT_PASSWORD_SMS: `A password reset has been requested. Your IP3 Portal one-time verification code is: [XXXX]. Do not share this code with anyone.`,
    FORGOT_PASSWORD_SUBJECT: 'L-ROI Portal Password Reset Request',
    FORGOT_PASSWORD_EMAIL: `<p>You are receiving this email because you requested a password reset for your IP3 Portal account. If you did not request this change, you can ignore this email.</p><p>To create a new password for your account, please enter the one-time verification code below when prompted.</p><p><strong>[XXXX]</strong></p><p>Do not share this code with anyone.</p>`,
    NEW_USER_EMAIL_SUBJECT: `L-ROI - Sign In`,
    NEW_EMPLOYEE_EMAIL: `<table width = "100%" border = "0" cellspacing = "0" cellpadding = "0" align = "center" > <tbody><tr><td height="30" align="center" style="font-size: 14px; padding-bottom: 10px; color:#666; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-weight: 400; background: #f5f5f5;">If you don't want to recieve this, kindly <a href="{{unsubscribeurl}}" style="color:#2B5E8D;">unsubscribe</a></td></tr><tr><th scope="col"><table border="0" style="background: #fff; max-width: 500px" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td align="center" style="padding:20px 10px;"><a href="#"><img src="https://L-ROIphotos.s3.ap-south-1.amazonaws.com/resources/logo.png" alt=""/></a></td></tr><tr><tr><th scope="col" align="left"><h1 style="font-size:18px; padding: 10px 40px 0; font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'">Hi {{firstname}}</h1></th></tr><tr><td style="padding: 0 40px; font-size: 14px; font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-weight: 400; line-height: 24px; color:#555;" align="left"><p>You have been registered as a user within L-ROI by {{orgname}}.</p><p>Your can install the application from playstore and login using your mobile number {{mobilenumber}}.</p></td></tr><tr><td height="20">&nbsp;</td></tr><tr><td height="10">&nbsp;</td></tr><td height="30" align="left" style="font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; color:#555; padding:20px 40px 40px; font-weight: 400;">Team<br> <strong>L-ROI</strong></td></tr></tbody></table></th></tr></tbody></table>`,
    NEW_USER_EMAIL: (link) => `<table width = "100%" border = "0" cellspacing = "0" cellpadding = "0" align = "center" > 
<tbody><tr><td height="30" align="center" style="font-size: 14px; padding-bottom: 10px; color:#666; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-weight: 400; background: #f5f5f5;">If you don't want to recieve this, kindly <a href="{{unsubscribeurl}}" style="color:#2B5E8D;">unsubscribe</a></td></tr>
<tr><th scope="col"><table border="0" style="background: #fff; max-width: 500px" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td align="center" style="padding:20px 10px;"><a href="#"><img src="https://L-ROIphotos.s3.ap-south-1.amazonaws.com/resources/logo.png" alt=""/></a></td></tr>
<tr><tr><th scope="col" align="left"><h1 style="font-size:18px; padding: 10px 40px 0; font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'">Hi {{firstname}}</h1></th></tr>
<tr><td style="padding: 0 40px; font-size: 14px; font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-weight: 400; line-height: 24px; color:#555;" align="left">
<p>You have been registered as a user within L-ROI.</p>
<p>Click this link to verify your email address and set your password: <a href="${link}" target="_blank">verify your email address</a></p>
</td></tr><tr><td height="20">&nbsp;</td></tr><tr><td height="10">&nbsp;</td></tr><td height="30" align="left" style="font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; color:#555; padding:20px 40px 40px; font-weight: 400;">Team<br> <strong>L-ROI</strong></td></tr></tbody></table></th></tr></tbody></table>`,
    LOGIN_OTP_SMS: "A sign in attempt has been made from a new device or browser. Your IP3 Portal one-time verification code is: [XXXX]. Do not share this code with anyone.",
    LOGIN_OTP_EMAIL: "<p>You are receiving this email because an attempt to sign in to your IP3 Portal account was made from a new device or browser.</p><p>If this wasn&rsquo;t you, please immediately reset your password. You can do this by selecting &ldquo;Forgot password?&rdquo; on the sign-in screen.</p><p>If this was you, please enter the one-time verification code below when prompted.</p><p><strong>[XXXX]</strong></p><p>Do not share this code with anyone.</p>",
    LOGIN_OTP_SUBJECT: `IP3 Portal Verification Code`,
    USER_SMS_OTP_VERIFY: "{{OTP}}+is+your+one+time+password.+Thank+you+for+using+L-ROI.",
    USER_EMAIL_OTP_VERIFY: `<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td height="30" align="center" style="font-size: 14px; padding-bottom: 10px; color:#666; font-family: 'Gill Sans', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-weight: 400; background: #f5f5f5;">If you don't want to recieve this, kindly <a href="{{unsubscribeurl}}" style="color:#2B5E8D;">unsubscribe</a></td></tr><tr><th scope="col"><table border="0" style="background: #fff; max-width: 500px" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td align="center" style="padding:20px 10px;"><a href="#"><img src="https://L-ROIphotos.s3.ap-south-1.amazonaws.com/resources/logo.png" alt=""/></a></td></tr><tr><tr><th scope="col" align="left"><h1 style="font-size:18px; padding: 10px 40px 0; font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'">Hi {{firstname}}</h1></th></tr><tr><td style="padding: 0 40px; font-size: 14px; font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-weight: 400; line-height: 24px; color:#555;" align="left"><p>Your password has been regenrated as per your request.</p><p>Your new one time password is <b>{{OTP}}</b>.</p></td></tr><tr><td height="20">&nbsp;</td></tr><tr><td height="10">&nbsp;</td></tr><td height="30" align="left" style="font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; color:#555; padding:20px 40px 40px; font-weight: 400;">Team<br> <strong>L-ROI</strong></td></tr></tbody></table></th></tr></tbody></table>`,
    EMAIL_LAYOUT_STD: `<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><th scope="col"><table border="0" style="background: #fff; max-width: 500px" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td align="center" style="padding:20px 10px;"><a href="#"><img src="https://L-ROIphotos.s3.eu-central-1.amazonaws.com/logo.png" alt=""/></a></td></tr><tr><tr><td style="padding: 0 40px; font-size: 14px; font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-weight: 400; line-height: 24px; color:#555;" align="left">{{ content }}</td></tr></tr></tbody></table></th></tr></tbody></table>`,
    REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
    REFRESH_TOKEN_EXPIRED: (message = 'Refresh Token has expired') => ({ success: "failure", message, code: "REFRESH_TOKEN_EXPIRED" }),
    OTP_HAS_EXPIRED: 'OTP_HAS_EXPIRED',
    otp_has_expired: (message = 'One time password has expired') => ({ success: "failure", message, code: "OTP_EXPIRED" }),
    MAX_OTP_FAILURE_ATTEMPTED: 'MAX_OTP_FAILURE_ATTEMPTED',
    MAX_OTP_FAILURE_ATTEMPTED: (message = 'One time password failure attempts has reached the max limit') => ({ success: "failure", message, code: "MAX_OTP_FAILURE_ATTEMPTED" }),
    OTP_FAILED_ATTEMPT: 'OTP_FAILED_ATTEMPT',
    otp_failed_attempt: (message = 'Invalid one time password provided') => ({ success: "failure", message, code: "OTP_FAILED_ATTEMPT" }),
    PASSWORD_CANT_BE_UPDATED: 'PASSWORD_CANT_BE_UPDATED',
    PASSWORD_CANT_BE_UPDATED: (message = 'The password provided can not be updated') => ({ success: "failure", message, code: "PASSWORD_CANT_BE_UPDATED" }),
    EMAIL_LAYOUT_STD: `<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tbody><tr><th scope="col"><table border="0" style="background: #fff; max-width: 500px" cellspacing="0" cellpadding="0" align="center"><tbody><tr><td align="center" style="padding:20px 10px;"><a href="#"><img src="https://L-ROIphotos.s3.eu-central-1.amazonaws.com/logo.png" alt=""/></a></td></tr><tr><tr><td style="padding: 0 40px; font-size: 14px; font-family: 'Roboto', 'Gill Sans MT', 'Myriad Pro', 'DejaVu Sans Condensed', Helvetica, Arial, 'sans-serif'; font-weight: 400; line-height: 24px; color:#555;" align="left">{{ content }}</td></tr></tr></tbody></table></th></tr></tbody></table>`,
    EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
    DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
    INVALID_EMAIL: (message= 'Invalid email address provided') => ({ success: "failure", message, code: "EMAIL_NOT_FOUND" }),
    OTP_NOT_SENT_SMS: 'OTP_NOT_SENT_SMS',
    OTP_NOT_SENT_ON_SMS: (message = 'One time password could not be sent on sms') => ({ success: "failure", message, code: "OTP_NOT_SENT_SMS" }),
    OTP_NOT_SENT_EMAIL: 'OTP_NOT_SENT_SMS',
    OTP_NOT_SENT_ON_EMAIL: (message = 'One time password could not be sent on email') => ({ success: "failure", message, code: "OTP_NOT_SENT_EMAIL" }),
    INVALID_REFRESH_TOKEN_PASSED: 'INVALID_REFRESH_TOKEN_PASSED',
    INVALID_REFRESH_TOKEN_PROVIDED: (message = 'Invalid refresh token was provided') => ({ success: "failure", message, code: "INVALID_REFRESH_TOKEN_PROVIDED" }),
    TOKEN_NOT_UPDATED: 'TOKEN_NOT_UPDATED',
    TOKEN_NOT_UPDATED: (message = 'Token could not be updated') => ({ success: "failure", message, code: "TOKEN_NOT_UPDATED" }),
    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
    TOKEN_NOT_FOUND: (message = 'Invalid token provided') => ({ success: "failure", message, code: "TOKEN_NOT_FOUND" }),
    REACHED_MAX_OTP_ATTEMPTS: 'REACHED_MAX_OTP_ATTEMPTS',
    MAX_OTP_ATTEMPTS: (message = 'One time password has reached the max attempts') => ({ success: "failure", message, code: "REACHED_MAX_OTP_ATTEMPTS" }),
    USER_DOESNT_EXIST: 'USER_DOESNT_EXIST',
    USER_NOT_FOUND: (message = 'User not found') => ({ success: "failure", message, code: "USER_DOESNT_EXIST" }),
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
    INVALID_ACCESS_TOKEN: (message = 'Invalid access token provided') => ({ success: "failure", message, code: "INVALID_ACCESS_TOKEN" }),
    EMAIL_OTP_NOT_FOUND: 'EMAIL_OTP_NOT_FOUND',
    OTP_NOT_FOUND_EMAIL: (message = 'email not found for email') => ({ success: "failure", message, code: "EMAIL_OTP_NOT_FOUND" }),
    INVALID_OTP_INPUT: 'INVALID_OTP_INPUT',
    INVALID_OTP: (message = 'Invalid one time password provided') => ({ success: "failure", message, code: "INVALID_OTP_INPUT" }),
    LOGIN_FAILED: 'LOGIN_FAILED',
    login_failed: (message = 'Could not login with the credentials provided') => ({ success: "failure", message, code: "LOGIN_FAILED" }),
    CREDENTIALS_BLOCKED: 'CREDENTIALS_BLOCKED',
    CREDENTIALS_LOCKED: (message = 'Credentials are locked') => ({ success: "failure", message, code: "CREDENTIALS_BLOCKED" }),
    INVALID_PASSWORD_MSG: 'INVALID_PASSWORD',
    INVALID_PASSWORD: (message = 'Invalid email/password provided') => ({ success: "failure", message, code: "INVALID_PASSWORD" }),
    INAVLID_TOKEN_OR_EMAIL: 'INAVLID_TOKEN_OR_EMAIL',
    INVALID_TOKEN_OR_EMAIL: (message = 'Invalid token or email provided') => ({ success: "failure", message, code: "INAVLID_TOKEN_OR_EMAIL" }),
    INVALID_ID_CODE: 'INAVLID_TOKEN_OR_EMAIL',
    INVALID_ID: (message = 'Invalid id provided') => ({ success: "failure", message, code: INAVLID_ID_CODE }),
    ACCESS_TOKEN_NOT_FOUND: (message = 'Access Token not found') => ({ success: "failure", message, code: "TOKEN_NOT_FOUND" }),
    ACCESS_TOKEN_NOT_PROVIDED: (message = 'Access Token not provided') => ({ success: "failure", message, code: "TOKEN_NOT_PROVIDED" }),
    PASSWORD_NOT_PROVIDED: (message = 'Please provide a password') => ({ success: "failure", message, code: "PASSWORD_NOT_PROVIDED" }),
    EMAIL_NOT_PROVIDED: (message = 'Please provide a email') => ({ success: "failure", message, code: "EMAIL_NOT_PROVIDED" }),
    NOT_VERIFIED: (message = 'Session has expired. Please log in again.') => ({ success: "failure", message, code: "SESSION_EXPIRED" }),
    FILE_NOT_FOUND: (message = 'File does not exist') => ({ success: "failure", message, code: "FILE_NOT_FOUND" }),
    twoFactorAuthEnabled: true,
    refreshTokenTTLInSeconds: 30 * 60,
    otpTTLInSeconds: 15 * 60,
    otpMaxFailureAttempts: 5,
    maxPasswordFailureAttempts: 10,
    credentialsBlockedFor: 0.5, // in hours,
    tokenTTLInSeconds: 60 * 60 * 24 * 30 , // 60 * 60 * 24 * 30
    accessTokenTTL: 30 * 60, // in seconds
});